version: '2.1'

services:
  php-apache:
    build: ops/docker/php-apache
    environment:
      DOCKER: 'true'
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    build: ops/docker/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: village-permissions
    ports:
      - 3306:3306

  composer:
    image: composer:latest
    depends_on:
      - php-apache
    command: install
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
